/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamehangman;

/**
 *
 * @author Maryam
 */
public class AdminCategories extends javax.swing.JFrame {

    /**
     * Creates new form AdminCategories
     */
    public AdminCategories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        categories = new javax.swing.JLabel();
        food = new javax.swing.JRadioButton();
        place = new javax.swing.JRadioButton();
        animal = new javax.swing.JRadioButton();
        display = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(153, 102, 0));
        title.setText("       HANG MAN");
        getContentPane().add(title);
        title.setBounds(170, 0, 360, 70);

        categories.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        categories.setForeground(new java.awt.Color(153, 102, 0));
        categories.setText("     CATEGORIES");
        getContentPane().add(categories);
        categories.setBounds(260, 80, 180, 70);

        food.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        food.setForeground(new java.awt.Color(255, 51, 51));
        food.setText("FOOD");
        food.setOpaque(false);
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        getContentPane().add(food);
        food.setBounds(290, 140, 90, 39);

        place.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        place.setForeground(new java.awt.Color(255, 51, 51));
        place.setText("PLACE");
        place.setOpaque(false);
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });
        getContentPane().add(place);
        place.setBounds(290, 200, 110, 39);

        animal.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        animal.setForeground(new java.awt.Color(255, 51, 51));
        animal.setText("ANIMAL");
        animal.setOpaque(false);
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });
        getContentPane().add(animal);
        animal.setBounds(290, 260, 120, 40);

        display.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        display.setForeground(new java.awt.Color(255, 51, 51));
        display.setText("DISPLAY");
        display.setOpaque(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(290, 320, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamehangman/34320wide.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
        AdminFood aFood=new AdminFood();
        aFood.setTitle("hangMan Game");
        aFood.setSize(700,550);
        aFood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_foodActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
        // TODO add your handling code here:
        AdminPlace place=new AdminPlace();
        place.setTitle("HangMan Game");
        place.setSize(700,550);
        place.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_placeActionPerformed

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
       AdminAnimals animal=new AdminAnimals();
       animal.setTitle("HangMan Game");
       animal.setSize(700,550);
       animal.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_animalActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        Display disp=new Display();
        disp.setTitle("HangMan Game");
        disp.setSize(700,550);
        disp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton animal;
    private javax.swing.JLabel categories;
    private javax.swing.JRadioButton display;
    private javax.swing.JRadioButton food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton place;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
