/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamehangman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maryam
 */
public class AdminPlace extends javax.swing.JFrame {

    /**
     * Creates new form AdminPlace
     */
    public AdminPlace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        placeLabel = new javax.swing.JLabel();
        addLabel = new javax.swing.JLabel();
        deleteLabel = new javax.swing.JLabel();
        addField = new javax.swing.JTextField();
        deleteField = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        dropButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(153, 102, 0));
        title.setText("       HANG MAN");
        getContentPane().add(title);
        title.setBounds(170, 0, 360, 70);

        placeLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        placeLabel.setForeground(new java.awt.Color(153, 102, 0));
        placeLabel.setText("Place");
        getContentPane().add(placeLabel);
        placeLabel.setBounds(290, 80, 130, 80);

        addLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        addLabel.setForeground(new java.awt.Color(255, 51, 51));
        addLabel.setText("Add");
        getContentPane().add(addLabel);
        addLabel.setBounds(70, 170, 70, 50);

        deleteLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        deleteLabel.setForeground(new java.awt.Color(255, 51, 51));
        deleteLabel.setText("Delete");
        getContentPane().add(deleteLabel);
        deleteLabel.setBounds(60, 240, 100, 50);

        addField.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        addField.setForeground(new java.awt.Color(0, 102, 0));
        addField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addField);
        addField.setBounds(210, 180, 240, 30);

        deleteField.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        deleteField.setForeground(new java.awt.Color(0, 102, 0));
        deleteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deleteField);
        deleteField.setBounds(210, 250, 240, 30);

        insertButton.setBackground(new java.awt.Color(255, 153, 102));
        insertButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        insertButton.setForeground(new java.awt.Color(0, 102, 0));
        insertButton.setText("Insert");
        insertButton.setContentAreaFilled(false);
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(insertButton);
        insertButton.setBounds(510, 170, 110, 39);

        dropButton.setBackground(new java.awt.Color(255, 153, 102));
        dropButton.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        dropButton.setForeground(new java.awt.Color(0, 102, 0));
        dropButton.setText("Drop");
        dropButton.setContentAreaFilled(false);
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dropButton);
        dropButton.setBounds(510, 240, 110, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamehangman/34320wide.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFieldActionPerformed

    private void deleteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            String s = addField.getText();
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/game";
            String usern="root";
            String passw="";
            Connection con=DriverManager.getConnection(url,usern,passw);
            String Query1 = "INSERT INTO datatable(Categories, data) VALUES (?,?)";
            PreparedStatement ps = con.prepareStatement(Query1);
            ps.setString(1,"Places");
            ps.setString(2,s);
            ps.execute();
            JOptionPane.showMessageDialog(null,"Place is successfully added!!",
                 "Hangman", JOptionPane.INFORMATION_MESSAGE);
            addField.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlace.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlace.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_insertButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
         String s= deleteField.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/game";
            String usern="root";
            String passw="";
            Connection con=DriverManager.getConnection(url,usern,passw);
            String Query1 ="DELETE FROM datatable WHERE data = ? ";
            PreparedStatement ps = con.prepareStatement(Query1);
            ps.setString(1,s);   
            ps.execute();
            JOptionPane.showMessageDialog(null,"Place is successfully deleted!!",
                 "Hangman", JOptionPane.INFORMATION_MESSAGE);
            deleteField.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlace.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlace.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_dropButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPlace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addField;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField deleteField;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JButton dropButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel placeLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
