package gamehangman;

import java.io.IOException;
import java.io.PrintStream;
import java.net.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Screen2 extends javax.swing.JFrame {

    String category;
    String user;
    String word;
    /**
     * Creates new form Screen2
     */
    public Screen2() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        categories = new javax.swing.JLabel();
        food = new javax.swing.JRadioButton();
        place = new javax.swing.JRadioButton();
        animal = new javax.swing.JRadioButton();
        pName = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(153, 102, 0));
        title.setText("     HANG MAN ");
        getContentPane().add(title);
        title.setBounds(190, 0, 300, 70);

        categories.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        categories.setForeground(new java.awt.Color(153, 102, 0));
        categories.setText("     CATEGORIES");
        getContentPane().add(categories);
        categories.setBounds(260, 80, 180, 70);

        food.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        food.setForeground(new java.awt.Color(255, 51, 51));
        food.setText("FOOD");
        food.setOpaque(false);
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        getContentPane().add(food);
        food.setBounds(290, 140, 90, 39);

        place.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        place.setForeground(new java.awt.Color(255, 51, 51));
        place.setText("PLACE");
        place.setOpaque(false);
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });
        getContentPane().add(place);
        place.setBounds(290, 200, 110, 39);

        animal.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        animal.setForeground(new java.awt.Color(255, 51, 51));
        animal.setText("ANIMAL");
        animal.setOpaque(false);
        animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalActionPerformed(evt);
            }
        });
        getContentPane().add(animal);
        animal.setBounds(290, 260, 120, 40);

        pName.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        pName.setForeground(new java.awt.Color(153, 102, 0));
        pName.setText("Player Name");
        getContentPane().add(pName);
        pName.setBounds(170, 400, 150, 50);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(330, 400, 210, 50);

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        start.setForeground(new java.awt.Color(153, 102, 0));
        start.setText("START");
        start.setToolTipText("");
        start.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        start.setBorderPainted(false);
        start.setContentAreaFilled(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(260, 470, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamehangman/34320wide.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
        category="Foods";
    }//GEN-LAST:event_foodActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
        // TODO add your handling code here:
        category="Places";
    }//GEN-LAST:event_placeActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        user=username.getText().trim();
    }//GEN-LAST:event_usernameActionPerformed
  
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        try {
            // TODO add your handling code here:
            //Socket clientSocket=new Socket("192.168.1.5",33000);
            Socket clientSocket=new Socket("127.0.0.1",1342);
            Scanner read=new Scanner(clientSocket.getInputStream());
            PrintStream sendMessage=new PrintStream(clientSocket.getOutputStream());
            sendMessage.println(category);
            if (read.hasNext())
            {
                word=read.next(); //recieve guess word                
            }
            user=username.getText().trim();
            System.out.println("word"+ word);
           System.out.println("screen2:"+user);
            Board game=new Board(user,category,word);
            game.setTitle("HangMan Game");
            game.setSize(710,550);
            game.setVisible(true);
            this.dispose();
              
        } catch (IOException ex) {
            Logger.getLogger(Screen2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startActionPerformed

    private void animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalActionPerformed
        // TODO add your handling code here:
        category="Animals";
    }//GEN-LAST:event_animalActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen2().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton animal;
    private javax.swing.JLabel categories;
    private javax.swing.JRadioButton food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pName;
    private javax.swing.JRadioButton place;
    private javax.swing.JButton start;
    private javax.swing.JLabel title;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
