/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamehangman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Maryam
 */
public class WinScreen extends javax.swing.JFrame {

    /**
     * Creates new form WinScreen
     */
    String player;
    String points;
    public WinScreen(String name,String score) {
        
        player=name;
        points=score;
        initComponents();
        System.out.println(name);
        nameField.setText(name);
        pointField.setText(points);
        
        //adding in database
         try {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/game";
            String user="root";
            String password="";
            Connection con=DriverManager.getConnection(url,user,password);
            System.out.println("connection established");
            String query = "INSERT INTO scoretable(Scores, userName) VALUES (?,?)";           
            PreparedStatement stat = con.prepareStatement(query);
            stat.setString(1,points);
            stat.setString(2,player);
            stat.execute();
            System.out.print("data updated");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Board.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Board.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }

    private WinScreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lost = new javax.swing.JLabel();
        playerName = new javax.swing.JLabel();
        nameField = new javax.swing.JLabel();
        scoreWin = new javax.swing.JLabel();
        pointField = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(153, 102, 0));
        title.setText("       HANG MAN");
        getContentPane().add(title);
        title.setBounds(170, 0, 360, 70);

        lost.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        lost.setForeground(new java.awt.Color(153, 102, 0));
        lost.setText("CONGRATULATION!");
        getContentPane().add(lost);
        lost.setBounds(160, 100, 390, 90);

        playerName.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        playerName.setForeground(new java.awt.Color(255, 102, 102));
        playerName.setText("Player:");
        getContentPane().add(playerName);
        playerName.setBounds(180, 200, 110, 70);

        nameField.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        nameField.setForeground(new java.awt.Color(51, 153, 0));
        nameField.setText("name");
        getContentPane().add(nameField);
        nameField.setBounds(380, 210, 210, 60);

        scoreWin.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        scoreWin.setForeground(new java.awt.Color(255, 102, 102));
        scoreWin.setText("Score:");
        getContentPane().add(scoreWin);
        scoreWin.setBounds(180, 280, 110, 70);

        pointField.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        pointField.setForeground(new java.awt.Color(51, 153, 0));
        pointField.setText("points");
        getContentPane().add(pointField);
        pointField.setBounds(380, 280, 210, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamehangman/34320wide.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 700, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel lost;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel pointField;
    private javax.swing.JLabel scoreWin;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
